### ISSUE TITLE
运行后，连不上直播间

### ISSUE THREAD

**Issue by turingzz** [YunzhiYike/live-tool#7]
![image](https://github.com/YunzhiYike/live-tool/assets/35909327/ef1ce523-347b-463e-8a75-d83a624057d6)

**Comment by YunzhiYike** [comment]
参考抖音开源仓库修改代码
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年08月05日 16:39 |
| 收件人 | YunzhiYike/live-tool ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | [YunzhiYike/live-tool] 运行后，连不上直播间 (Issue #7) |

**Comment by turingzz** [comment]
多谢
